version: "3"

services:
  water_pred:
    build:
      context: ./waterpred/
      dockerfile: Dockerfile
    container_name: waterpred
    restart: always
    ports:
      - 8080:8080
    volumes:
      - water_data:/waterpred/water_cons
    networks:
      - mynetwork

  reedata:
    build:
      context: ./reedata/
      dockerfile: Dockerfile
    container_name: reedata
    restart: always
    ports:
      - 8082:8082
    volumes:
      - ree_data:/reedata/gen_dem

  smartgen:
    build:
      context: ./smartgen/
      dockerfile: Dockerfile
    container_name: smartgen
    restart: always
    ports:
      - 8081:8081
    volumes:
      - water_data:/smartgen/water_cons
      - ree_data:/smartgen/gen_dem
    networks:
      - mynetwork

volumes:
  influxdb:
  water_data:
  ree_data:

networks:
  mynetwork:
    name: mynetwork
    external: true
