# Use an official Python runtime as a parent image
FROM python:3.9-slim

# RUN echo "hello world"

# # Set the working directory to /app
WORKDIR /waterpred

# RUN pwd
# # Copy the current directory contents into the container at /app
COPY . ./waterpred

# # # Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r ./waterpred/requirements.txt

RUN pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu

# # # Define environment variable
ENV NAME World

# Fill the database
# RUN python ./waterpred/writeInfluxDB.py


RUN mkdir water_cons

RUN touch ./water_cons/command.txt

RUN touch ./water_cons/results.txt

# # # Run app.py when the container launches
CMD ["python", "./waterpred/waterPrediction.py"]