# Use an official Python runtime as a parent image
FROM python:3.9-slim

# RUN echo "hello world"

# # Set the working directory to /app
WORKDIR /reedata

# RUN pwd
# # Copy the current directory contents into the container at /app
COPY . ./reedata

# # # Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r ./reedata/requirements.txt

# # # Make port 80 available to the world outside this container
EXPOSE 8082

# # # Define environment variable
ENV NAME World

# Fill the database
# RUN python ./reedata/writeInfluxDB.py

RUN mkdir gen_dem

RUN touch gen_dem/command.txt

RUN touch gen_dem/results.txt

# # # Run app.py when the container launches
CMD ["python", "./reedata/getREEdata.py"]